apiVersion: v1
kind: Secret
metadata:
  name: objectstorage-secret
  namespace: examyandexapp
type: Opaque
data:
  access-key: WUNBSkVzaDFoZGh4M1RrYVcxVmdrNU8zag==
  secret-key: WUNOVWR6Zko0RGVqR0owako4NEIzTFRtWldQLUR6TmQ4SS00aUN1MA==
  bucket-name: ZXhhbXlhbmRleGFwcC1pbWFnZXM=