apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: examyandexapp
type: Opaque
data:
  db-host: cmMxYi10cHRhaWU3Mm1udGJvcWR2Lm1kYi55YW5kZXhjbG91ZC5uZXQ=
  db-port: NjQzMg==
  db-name: ZXhhbXlhbmRleGFwcA==
  db-user: dXNlcg==
  db-password: YmFyczE5OTU=