apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: examyandexapp
type: Opaque
data:
  db-password: WW91clBhc3N3b3JkMTIzIQ==  # YourPassword123! в base64
  sa-password: WW91clBhc3N3b3JkMTIzIQ==  # YourPassword123! в base64